import Link from "next/link";
import type { Metadata } from "next";
import { PublicNav } from "@/app/components/PublicNav";
import { BillingButton } from "@/app/components/BillingButton";
import { billingEnabled } from "@/lib/billing/stripe";
import { PLANS } from "@/lib/billing/plans";
export const metadata: Metadata = { title: "Planes en pesos — Sakatl" };
export const dynamic = "force-dynamic";
export default function PlanesPage() {
  const enabled = billingEnabled();
  const test = !process.env.STRIPE_SECRET_KEY?.includes("_live_");
  return <div className="min-h-screen bg-[#0d0f12] text-[#f1f3f4]"><PublicNav /><main className="mx-auto max-w-6xl px-5 py-12 md:py-20">
    <div className="mb-10 max-w-2xl"><p className="mb-4 text-xs font-bold tracking-[.18em] text-[#4ade80] uppercase">Entrena a tu ritmo</p><h1 className="text-4xl font-extrabold md:text-6xl">Empieza gratis.<br />Dale más espacio a tu rutina.</h1><p className="mt-5 text-lg text-[#9099a3]">Precios en pesos mexicanos. Tu historial sigue siendo tuyo, con cualquier plan.</p>{enabled && test && <p className="mt-4 rounded-xl border border-amber-500/30 bg-amber-500/10 p-3 text-sm text-amber-200">Entorno de pruebas. No se realizan cobros reales.</p>}</div>
    <div className="grid gap-5 lg:grid-cols-3">
      <section className="flex flex-col rounded-2xl border border-[#2a2f37] bg-[#1c2026] p-7"><h2 className="text-xl font-bold">Gratis</h2><p className="my-6 text-5xl font-extrabold">$0 <span className="text-sm font-normal text-[#9099a3]">MXN</span></p><ul className="mb-8 space-y-3 text-sm text-[#9099a3]">{["Hasta 4 rutinas guardadas", "Registro e historial de entrenamientos", "Biblioteca, calendario y estadísticas", "Mensajes de IA sin cupos por ahora", "Transcripciones sin cupos por ahora"].map(x => <li key={x}>✓ {x}</li>)}</ul><Link href="/sign-up" className="mt-auto rounded-xl border border-[#2a2f37] px-4 py-3 text-center font-bold">Crear cuenta gratis</Link></section>
      {Object.entries(PLANS).map(([key,plan]) => <section key={key} className={`flex flex-col rounded-2xl border p-7 ${key === "month" ? "border-[#4ade80] bg-[#14261c]" : "border-[#2a2f37] bg-[#1c2026]"}`}><h2 className="text-xl font-bold">Pro · {plan.label}</h2><p className="my-6 text-5xl font-extrabold">${plan.amount/100} <span className="text-sm font-normal text-[#9099a3]">MXN/{key === "month" ? "mes" : "año"}</span></p><p className="mb-5 text-sm text-[#4ade80]">{key === "year" ? "$41.58 al mes, en un pago anual. Ahorra 29.5%." : "Sin permanencia obligatoria."}</p><ul className="mb-8 space-y-3 text-sm text-[#9099a3]">{["Todo lo incluido en Gratis", "Rutinas sin límite de cantidad", "Mensajes de IA sin cupos por ahora", "Transcripciones sin cupos por ahora", "Cancela la renovación desde tu cuenta"].map(x => <li key={x}>✓ {x}</li>)}</ul><div className="mt-auto"><BillingButton interval={plan.interval} enabled={enabled} /></div></section>)}
    </div><div className="mt-8 space-y-3 text-sm text-[#9099a3]"><p>Importes finales con impuestos incluidos. Por ahora el uso de IA está disponible sin cupos. Cada audio admite hasta 5 MB. El asistente usa los mensajes recientes como contexto, hasta 24 mensajes y 32,000 caracteres; el historial anterior se recorta automáticamente para continuar.</p><p>Al cancelar conservas acceso hasta terminar el período pagado. No borramos tus rutinas ni tu historial por cambiar de plan. </p><p>El asistente propone rutinas que tú revisas antes de guardar. No sustituye atención médica ni entrenamiento profesional individual.</p><p className="flex flex-wrap gap-5"><Link href="/app/plan" className="text-[#4ade80] underline">Mi plan</Link><Link href="/terminos" className="underline">Términos</Link><Link href="/privacidad" className="underline">Privacidad</Link></p></div>
  </main></div>;
}
